print("Lima Menit Mengenal Saya")

print(">>>>>>>><<<<<<<<")

nama = str("Rizky Ammar surya Saputra")
ttl = str("Jakarta, 01 Februari 2002")
umur = int(19)
nim = str("I0320087")
ft = str("Fakultas Teknik")
id = str("Industri")
at = int("2020")
bb = float("68.5")
tb = float("170.05")
us = int("43")
ar = str("Jl Klebet V, Jebres, Surakarta")

print("Dibawah ini berisi Biodata saya")
print("<<<<<<<<>>>>>>>>")

print("1. Nama : ", nama)
print("2. Tempat, tanggal lahir : ", ttl)
print("3. Alamat Kost : ", ar)
print("4. umur : ", umur)
print("5. Fakultas : ", ft)
print("6. Jurusan : ", id)
print("7. NIM : ", nim)
print("8. Angkatan : ", at)
print("9. Berat Badan : ", bb)
print("10. Tinggi Badan : ", tb)
print("11. Ukuran Sepatu : ", us)


print("Terima Kasih Telah Membaca Biodata Saya")
print(">>>>>>>><<<<<<<<")
print("<<<<<<<<>>>>>>>>")